"""Obecný registr psích plemen (FCI/ČMKU), česky.

Používá se jako zdroj nabídky pro `<datalist>` u pole „Plemeno" v profilu psa.
Pole zůstává volný text – pokud plemeno v seznamu není, uživatel ho napíše ručně.
„Kříženec" je záměrně první, aby byl hned po ruce.
"""

DOG_BREEDS = [
    "Kříženec",
    "Afghánský chrt",
    "Aljašský malamut",
    "Americká akita",
    "Americký buldok",
    "Americký kokršpaněl",
    "Americký stafordšírský teriér",
    "Anglický buldok",
    "Anglický kokršpaněl",
    "Anglický setr",
    "Anglický špringršpaněl",
    "Australský honácký pes",
    "Australský ovčák",
    "Australská kelpie",
    "Australský teriér",
    "Barzoj",
    "Basenji",
    "Basset hound",
    "Bavorský barvář",
    "Bearded kolie",
    "Bedlington teriér",
    "Belgický ovčák groenendael",
    "Belgický ovčák laekenois",
    "Belgický ovčák malinois",
    "Belgický ovčák tervueren",
    "Bernský salašnický pes",
    "Bígl",
    "Bílý švýcarský ovčák",
    "Bišon frisé",
    "Bloodhound",
    "Bordeauxská doga",
    "Border kolie",
    "Border teriér",
    "Boston teriér",
    "Boxer",
    "Bretaňský ohař",
    "Briard",
    "Bruselský grifonek",
    "Bulmastif",
    "Bullteriér",
    "Cairn teriér",
    "Cane corso",
    "Čau-čau",
    "Československý vlčák",
    "Čínský chocholatý pes",
    "Čivava",
    "Dalmatin",
    "Dobrman",
    "Entlebušský salašnický pes",
    "Erdelteriér",
    "Eurasier",
    "Field španěl",
    "Flat coated retrívr",
    "Foxteriér drsnosrstý",
    "Foxteriér hladkosrstý",
    "Francouzský buldoček",
    "Gordonsetr",
    "Grónský pes",
    "Havanský psík",
    "Hovawart",
    "Chodský pes",
    "Irský červenobílý setr",
    "Irský setr",
    "Irský teriér",
    "Irský vlkodav",
    "Irský vodní španěl",
    "Islandský ovčák",
    "Italský chrtík",
    "Jack Russell teriér",
    "Japonský chin",
    "Japonský špic",
    "Kanárská doga",
    "Kavalír king charles španěl",
    "Kavkazský pastevecký pes",
    "Keeshond",
    "King charles španěl",
    "Knírač malý",
    "Knírač střední",
    "Knírač velký",
    "Kolie dlouhosrstá",
    "Kolie krátkosrstá",
    "Komondor",
    "Kuvasz",
    "Labradorský retrívr",
    "Lagotto romagnolo",
    "Landseer",
    "Leonberger",
    "Lhasa apso",
    "Löwchen",
    "Maďarský ohař drátosrstý",
    "Maďarský ohař krátkosrstý (vizsla)",
    "Maltézský psík",
    "Manchester teriér",
    "Mastif",
    "Mexický naháč",
    "Mops",
    "Německá doga",
    "Německý drátosrstý ohař",
    "Německý krátkosrstý ohař",
    "Německý křepelák",
    "Německý ovčák",
    "Německý pinč",
    "Německý špic malý",
    "Německý špic střední",
    "Německý špic velký",
    "Novofundlandský pes",
    "Norfolk teriér",
    "Norwich teriér",
    "Nova scotia duck tolling retrívr",
    "Papillon",
    "Parson russell teriér",
    "Pekinéz",
    "Pointer",
    "Portugalský vodní pes",
    "Pražský krysařík",
    "Pudl malý",
    "Pudl střední",
    "Pudl trpasličí",
    "Pudl velký",
    "Pumi",
    "Pyrenejský horský pes",
    "Pyrenejský ovčák",
    "Rhodéský ridgeback",
    "Rotvajler",
    "Ruský toy",
    "Samojed",
    "Šarpej",
    "Šeltie",
    "Schipperke",
    "Scottish teriér",
    "Shiba inu",
    "Sibiřský husky",
    "Silky teriér",
    "Slovenský čuvač",
    "Slovenský hrubosrstý ohař",
    "Slovenský kopov",
    "Špringršpaněl",
    "Stabyhoun",
    "Stafordšírský bulteriér",
    "Svatobernardský pes (bernardýn)",
    "Tibetský mastif",
    "Tibetský španěl",
    "Tibetský teriér",
    "Trpasličí pinč",
    "Velšteriér",
    "Výmarský ohař",
    "Welsh corgi cardigan",
    "Welsh corgi pembroke",
    "West highland white teriér",
    "Whippet",
    "Yorkšírský teriér",
    "Zlatý retrívr",
]
