# Generated by Django 5.2.9 on 2026-01-04 12:16

from django.conf import settings
from django.db import migrations


def rename_coursesaccess_table(apps, schema_editor):
    tables = set(schema_editor.connection.introspection.table_names())
    old_table = "payments_coursesaccess"
    new_table = "payments_courseaccess"

    if old_table in tables and new_table not in tables:
        schema_editor.alter_db_table(None, old_table, new_table)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_module_pdf_file_alter_module_vimeo_embed_url1_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    rename_coursesaccess_table,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RenameModel(
                    old_name='CoursesAccess',
                    new_name='CourseAccess',
                ),
            ],
        ),
    ]
