# Generated by Django 5.2.9 on 2026-01-04 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_module_pdf_file_alter_module_vimeo_embed_url1_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursesAccess',
            new_name='CourseAccess',
        ),
    ]
