# Generated by Django 5.2.9 on 2026-01-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_order_city_order_country_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, help_text='Číslo faktury – generuje se po zaplacení', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
