# Generated by Django 5.2.9 on 2026-01-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_order_invoice_number_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False, help_text='Souhlas se zasíláním newsletteru'),
        ),
    ]
