# Generated by Django 5.2.9 on 2026-02-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_product_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='course',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_czk',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.courseplan'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='bullets',
            field=models.TextField(blank=True, help_text='Jedna položka na řádek'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Krátký podtitulek pod názvem', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Košík'), ('pending', 'Čeká na platbu'), ('paid', 'Zaplaceno'), ('failed', 'Neúspěšné'), ('canceled', 'Zrušeno')], default='cart', max_length=20),
        ),
    ]
