# Generated by Django 5.2.9 on 2026-02-18 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_moduleprogress'),
        ('payments', '0009_remove_order_course_remove_order_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplan',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='courses.course'),
            preserve_default=False,
        ),
    ]
