# Generated by Django 5.2.9 on 2026-06-02 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_options_alter_courseplan_options_and_more'),
        ('payments', '0014_courseaccess_bypass_module_sequencing'),
        ('shop', '0005_alter_cartitem_course_plan_alter_cartitem_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseaccess',
            options={'ordering': ['-granted_at'], 'verbose_name': 'Přístup ke kurzu', 'verbose_name_plural': 'Přístupy ke kurzům'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Objednávka', 'verbose_name_plural': 'Objednávky'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Položka objednávky', 'verbose_name_plural': 'Položky objednávky'},
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Výše slevy z kupónu uplatněná na tuto objednávku.', max_digits=10, verbose_name='Sleva'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='bypass_module_sequencing',
            field=models.BooleanField(default=False, help_text='Pokud je zapnuto, zákazník nemusí procházet moduly v pořadí.', verbose_name='Povolit přeskakování modulů'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='courses.course', verbose_name='Kurz'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Přístup vyprší'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='granted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Přístup udělen'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='courses.courseplan', verbose_name='Zakoupená varianta'),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Zákazník'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='CZ', max_length=2, verbose_name='Země'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Fakturační město'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_country',
            field=models.CharField(blank=True, default='CZ', max_length=2, verbose_name='Fakturační země'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fakturační jméno / firma'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Číslo faktury'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Faktura (PDF)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fakturační ulice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fakturační PSČ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='order',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False, verbose_name='Přihlášen k newsletteru'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packeta_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Packeta – vytvořeno'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packeta_label_pdf',
            field=models.FileField(blank=True, null=True, upload_to='packeta_labels/', verbose_name='Packeta – štítek (PDF)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packeta_packet_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Packeta – ID zásilky'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packeta_point_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Packeta – ID výdejního místa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packeta_point_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Packeta – výdejní místo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packeta_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Packeta – sledovací číslo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('zasilkovna', 'Zásilkovna'), ('kuryr', 'Kurýr')], max_length=50, null=True, verbose_name='Způsob dopravy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena dopravy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Košík'), ('pending', 'Čeká na platbu'), ('paid', 'Zaplaceno'), ('failed', 'Neúspěšné'), ('canceled', 'Zrušeno')], default='cart', max_length=20, verbose_name='Stav objednávky'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_reduced',
            field=models.BooleanField(default=False, verbose_name='Sklad odečten'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ulice a číslo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe – ID platební relace'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe – ID platby'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Zákazník'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='course_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courseplan', verbose_name='Varianta kurzu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order', verbose_name='Objednávka'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena při nákupu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant', verbose_name='Varianta produktu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Množství'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Kód, který zákazník zadá v košíku, např. VANOCE20.', max_length=40, unique=True, verbose_name='Kód kupónu')),
                ('description', models.CharField(blank=True, help_text='Krátký popis pro orientaci v seznamu kupónů.', max_length=255, verbose_name='Název / popis')),
                ('discount_type', models.CharField(choices=[('percent', 'Procentuální sleva (%)'), ('fixed', 'Pevná částka (Kč)')], default='percent', max_length=10, verbose_name='Typ slevy')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='U procentuální slevy zadej číslo 0–100, u pevné částky hodnotu v Kč.', max_digits=10, verbose_name='Výše slevy')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Platný od')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Platný do')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Nech prázdné pro neomezené použití.', null=True, verbose_name='Maximální počet použití')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Kolikrát už byl kupón uplatněn (počítá se automaticky).', verbose_name='Počet použití')),
                ('max_uses_per_user', models.PositiveIntegerField(blank=True, help_text='Nech prázdné, pokud nechceš omezovat počet použití na zákazníka.', null=True, verbose_name='Max. použití na jednoho zákazníka')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Kupón půjde uplatnit až od této hodnoty zboží v košíku.', max_digits=10, verbose_name='Minimální hodnota objednávky (Kč)')),
                ('note', models.TextField(blank=True, verbose_name='Interní poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('courses', models.ManyToManyField(blank=True, help_text='Nech prázdné = platí pro všechny kurzy.', related_name='coupons', to='courses.course', verbose_name='Platí pouze pro kurzy')),
                ('products', models.ManyToManyField(blank=True, help_text='Nech prázdné = platí pro všechny produkty.', related_name='coupons', to='shop.product', verbose_name='Platí pouze pro produkty')),
                ('user', models.ForeignKey(blank=True, help_text='Nech prázdné = kupón může použít kdokoli.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_coupons', to=settings.AUTH_USER_MODEL, verbose_name='Platí pouze pro zákazníka')),
            ],
            options={
                'verbose_name': 'Slevový kupón',
                'verbose_name_plural': 'Slevové kupóny',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.coupon', verbose_name='Použitý kupón'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Uplatněná sleva (Kč)')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Použito')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.coupon', verbose_name='Kupón')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='payments.order', verbose_name='Objednávka')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='Zákazník')),
            ],
            options={
                'verbose_name': 'Použití kupónu',
                'verbose_name_plural': 'Použití kupónů',
                'ordering': ['-used_at'],
            },
        ),
    ]
