# Generated by Django 5.2.9 on 2026-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_db_schema_repair_fresh_deployments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zaplaceno'),
        ),
        migrations.AddField(
            model_name='order',
            name='review_request_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Žádost o recenzi odeslána'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='shop_locked',
            field=models.BooleanField(default=False, help_text='Zaškrtněte pro docasne uzamceni kosiku a tlacítek Pridat do kosiku. Stranky kurzu a produktu zustavaji dostupne. Existujici pristupy ke kurzum nejsou dotceny.', verbose_name='Prodej uzamčen'),
        ),
    ]
