# Generated by Django 5.2.9 on 2026-07-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_welcomecouponclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='Jméno')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Příjmení')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='Odebírá')),
                ('source', models.CharField(blank=True, default='checkout', max_length=50, verbose_name='Zdroj souhlasu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Souhlas udělen')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
            ],
            options={
                'verbose_name': 'Odběratel newsletteru',
                'verbose_name_plural': 'Odběratelé newsletteru',
                'ordering': ('-created_at',),
            },
        ),
    ]
