# Generated by Django 5.2.9 on 2026-07-14 06:28

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_backfill_newsletter_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/denisa/PycharmProjects/Mamka_kurz/private_media')), upload_to='invoices/', verbose_name='Faktura (PDF)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='packeta_label_pdf',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/denisa/PycharmProjects/Mamka_kurz/private_media')), upload_to='packeta_labels/', verbose_name='Packeta – štítek (PDF)'),
        ),
    ]
