# Generated by Django 5.2.9 on 2026-07-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_order_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_ico',
            field=models.CharField(blank=True, max_length=20, verbose_name='IČO'),
        ),
    ]
