# Generated by Django 5.2.9 on 2026-07-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_order_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doručeno / vyzvednuto'),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Předáno dopravci'),
        ),
        migrations.AddField(
            model_name='order',
            name='packeta_last_status_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Packeta – poslední kód stavu'),
        ),
        migrations.AddField(
            model_name='order',
            name='packeta_last_status_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Packeta – poslední stav (text)'),
        ),
        migrations.AddField(
            model_name='order',
            name='packeta_status_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Poslední kontrola stavu'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_barcode_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vratkový kód'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_packet_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Packeta – ID vratkové zásilky'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vratka vyžádána'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('processing', 'Zpracovává se'), ('shipped', 'Odesláno'), ('delivered', 'Doručeno')], default='processing', max_length=20, verbose_name='Stav zásilky'),
        ),
    ]
