# Generated by Django 5.2.9 on 2026-07-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_order_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='heureka_opt_in',
            field=models.BooleanField(default=False, verbose_name='Souhlas s Heureka Ověřeno zákazníky'),
        ),
        migrations.AddField(
            model_name='order',
            name='heureka_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heureka – odesláno'),
        ),
    ]
