# Generated by Django 5.2.9 on 2026-07-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_order_heureka_fields'),
        ('payments', '0024_order_invoice_ico_alter_order_invoice_pdf_and_more'),
    ]

    operations = [
    ]
