# Generated by Django 5.2.9 on 2026-02-27 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='CZ', max_length=2)),
                ('invoice_name', models.CharField(blank=True, max_length=255)),
                ('invoice_street', models.CharField(blank=True, max_length=255)),
                ('invoice_city', models.CharField(blank=True, max_length=120)),
                ('invoice_zip', models.CharField(blank=True, max_length=20)),
                ('invoice_country', models.CharField(blank=True, default='CZ', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
