# Generated by Codex on 2026-05-05

from django.db import migrations, models


def sync_existing_staff_roles(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")

    UserProfile.objects.filter(
        user__is_staff=True,
    ).update(role="admin")
    UserProfile.objects.filter(
        user__is_superuser=True,
    ).update(role="admin")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Uživatel"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.RunPython(sync_existing_staff_roles, migrations.RunPython.noop),
    ]
