# Generated by Django 5.2.9 on 2026-06-02 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil zákazníka', 'verbose_name_plural': 'Profily zákazníků'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='CZ', max_length=2, verbose_name='Země'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invoice_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Fakturační město'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invoice_country',
            field=models.CharField(blank=True, default='CZ', max_length=2, verbose_name='Fakturační země'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fakturační jméno / firma'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invoice_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fakturační ulice'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invoice_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fakturační PSČ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Uživatel'), ('admin', 'Admin')], default='user', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ulice a číslo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PSČ'),
        ),
    ]
