# Generated by Django 5.2.9 on 2026-07-12 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_options_alter_userprofile_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Jméno psa')),
                ('breed', models.CharField(blank=True, max_length=160, verbose_name='Plemeno')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Pes'), ('female', 'Fena')], max_length=10, verbose_name='Pohlaví')),
                ('notes', models.TextField(blank=True, verbose_name='Poznámky')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to=settings.AUTH_USER_MODEL, verbose_name='Majitel')),
            ],
            options={
                'verbose_name': 'Pes',
                'verbose_name_plural': 'Psi',
                'ordering': ['name'],
            },
        ),
    ]
