# Generated by Django 5.2.9 on 2026-07-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_email_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='chip_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Číslo čipu / tetování'),
        ),
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.CharField(blank=True, max_length=80, verbose_name='Barva srsti'),
        ),
        migrations.AddField(
            model_name='dog',
            name='dewormed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Poslední odčervení'),
        ),
        migrations.AddField(
            model_name='dog',
            name='diet',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dieta / krmení'),
        ),
        migrations.AddField(
            model_name='dog',
            name='is_neutered',
            field=models.CharField(blank=True, choices=[('yes', 'Ano'), ('no', 'Ne')], max_length=3, verbose_name='Kastrace'),
        ),
        migrations.AddField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='dogs/', verbose_name='Fotografie'),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccinated_on',
            field=models.DateField(blank=True, null=True, verbose_name='Poslední očkování'),
        ),
        migrations.AddField(
            model_name='dog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hmotnost (kg)'),
        ),
    ]
