# Generated by Django 5.2.9 on 2026-07-14 06:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_dog_chip_number_dog_color_dog_dewormed_on_dog_diet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False, verbose_name='Souhlas se zasíláním marketingových e-mailů'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marketing_consent_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Souhlas aktualizován'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review_request_opt_in',
            field=models.BooleanField(default=True, verbose_name='Žádost o recenzi po nákupu'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='dogs/', validators=[accounts.models.validate_photo_size], verbose_name='Fotografie'),
        ),
    ]
