# Generated by Django 5.2.9 on 2026-01-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='vimeo_embed_url',
            new_name='vimeo_embed_url1',
        ),
        migrations.AddField(
            model_name='module',
            name='vimeo_embed_url2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='vimeo_embed_url3',
            field=models.URLField(blank=True),
        ),
    ]
