# Generated by Django 5.2.9 on 2026-01-03 11:37

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_vimeo_embed_url_module_vimeo_embed_url1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='module_pdfs/', validators=[courses.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='module',
            name='vimeo_embed_url1',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(message='Zadej Vimeo embed URL ve tvaru https://player.vimeo.com/video/123456789', regex='^https:\\/\\/player\\.vimeo\\.com\\/video\\/\\d+.*$')]),
        ),
        migrations.AlterField(
            model_name='module',
            name='vimeo_embed_url2',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(message='Zadej Vimeo embed URL ve tvaru https://player.vimeo.com/video/123456789', regex='^https:\\/\\/player\\.vimeo\\.com\\/video\\/\\d+.*$')]),
        ),
        migrations.AlterField(
            model_name='module',
            name='vimeo_embed_url3',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(message='Zadej Vimeo embed URL ve tvaru https://player.vimeo.com/video/123456789', regex='^https:\\/\\/player\\.vimeo\\.com\\/video\\/\\d+.*$')]),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_order_per_course'),
        ),
    ]
