# Generated by Django 5.2.9 on 2026-02-27 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_course_created_at_course_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplan',
            name='access_duration_days',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_3c7e41_idx'),
        ),
        migrations.AddIndex(
            model_name='courseplan',
            index=models.Index(fields=['course'], name='courses_cou_course__60b557_idx'),
        ),
        migrations.AddIndex(
            model_name='courseplan',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_db0efe_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['user'], name='courses_mod_user_id_84b3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['module'], name='courses_mod_module__1fb606_idx'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='unique_slug_per_course'),
        ),
    ]
