# Generated by Django 5.2.9 on 2026-04-05 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseplan_access_duration_days_alter_module_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleQuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('passed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progresses', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'module'], name='courses_mod_user_id_fbe5e1_idx'), models.Index(fields=['module', 'step'], name='courses_mod_module__c29f53_idx')],
                'unique_together': {('user', 'module', 'step')},
            },
        ),
    ]
