# Generated by Django 5.2.9 on 2026-05-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_modulequizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coming_soon',
            field=models.BooleanField(default=False, help_text='Kurz se připravuje – zobrazí se informace a tlačítko Přidat do košíku bude skryté.'),
        ),
    ]
