# Generated by Django 5.2.9 on 2026-06-02 15:16

import courses.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_coming_soon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurz', 'verbose_name_plural': 'Kurzy'},
        ),
        migrations.AlterModelOptions(
            name='courseplan',
            options={'verbose_name': 'Varianta kurzu', 'verbose_name_plural': 'Varianty kurzu'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Modul', 'verbose_name_plural': 'Moduly'},
        ),
        migrations.AlterModelOptions(
            name='moduleprogress',
            options={'verbose_name': 'Postup v modulu', 'verbose_name_plural': 'Postup v modulech'},
        ),
        migrations.AlterModelOptions(
            name='modulequizprogress',
            options={'verbose_name': 'Postup v kvízu', 'verbose_name_plural': 'Postup v kvízech'},
        ),
        migrations.AlterField(
            model_name='course',
            name='about_text',
            field=models.TextField(blank=True, verbose_name='O kurzu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coming_soon',
            field=models.BooleanField(default=False, help_text='Kurz se připravuje – zobrazí se informace a tlačítko Přidat do košíku bude skryté.', verbose_name='Připravujeme'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses/', verbose_name='Obrázek kurzu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='course',
            name='private_intro',
            field=models.TextField(blank=True, verbose_name='Úvod po zakoupení'),
        ),
        migrations.AlterField(
            model_name='course',
            name='public_intro',
            field=models.TextField(blank=True, verbose_name='Veřejný úvod'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL adresa (slug)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Název kurzu'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='access_duration_days',
            field=models.PositiveIntegerField(default=180, help_text='Po kolika dnech od zakoupení přístup vyprší (180 = půl roku).', verbose_name='Délka přístupu (dny)'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='code',
            field=models.SlugField(verbose_name='Kód varianty'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='courses.course', verbose_name='Kurz'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='includes_certificate',
            field=models.BooleanField(default=False, verbose_name='Obsahuje certifikát'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='includes_consultation',
            field=models.BooleanField(default=False, verbose_name='Obsahuje konzultaci'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název varianty'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Kurz'),
        ),
        migrations.AlterField(
            model_name='module',
            name='intro_text',
            field=models.TextField(blank=True, verbose_name='Úvodní text'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Pořadí'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='module_pdfs/', validators=[courses.models.validate_pdf], verbose_name='PDF materiál'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='URL adresa (slug)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Název modulu'),
        ),
        migrations.AlterField(
            model_name='module',
            name='vimeo_embed_url1',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(message='Zadej Vimeo embed URL ve tvaru https://player.vimeo.com/video/123456789', regex='^https:\\/\\/player\\.vimeo\\.com\\/video\\/\\d+.*$')], verbose_name='Vimeo video 1'),
        ),
        migrations.AlterField(
            model_name='module',
            name='vimeo_embed_url2',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(message='Zadej Vimeo embed URL ve tvaru https://player.vimeo.com/video/123456789', regex='^https:\\/\\/player\\.vimeo\\.com\\/video\\/\\d+.*$')], verbose_name='Vimeo video 2'),
        ),
        migrations.AlterField(
            model_name='module',
            name='vimeo_embed_url3',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator(message='Zadej Vimeo embed URL ve tvaru https://player.vimeo.com/video/123456789', regex='^https:\\/\\/player\\.vimeo\\.com\\/video\\/\\d+.*$')], verbose_name='Vimeo video 3'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Dokončeno'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dokončeno dne'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='moduleprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zákazník'),
        ),
        migrations.AlterField(
            model_name='modulequizprogress',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Počet pokusů'),
        ),
        migrations.AlterField(
            model_name='modulequizprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progresses', to='courses.module', verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='modulequizprogress',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Splněno'),
        ),
        migrations.AlterField(
            model_name='modulequizprogress',
            name='passed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Splněno dne'),
        ),
        migrations.AlterField(
            model_name='modulequizprogress',
            name='step',
            field=models.PositiveSmallIntegerField(verbose_name='Krok kvízu'),
        ),
        migrations.AlterField(
            model_name='modulequizprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zákazník'),
        ),
    ]
