# Generated by Django 5.2.9 on 2026-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='length',
            field=models.CharField(blank=True, choices=[('7', '7 metrů'), ('10', '10 metrů')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='type',
            field=models.CharField(blank=True, choices=[('no_loop', 'Bez očka'), ('shoulder', 'Očko přes rameno'), ('hand_loop', 'Poutko na ruku')], max_length=20, null=True),
        ),
    ]
