# Generated by Django 5.2.9 on 2026-02-27 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_course_created_at_course_image_and_more'),
        ('shop', '0003_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Položka košíku', 'verbose_name_plural': 'Položky košíku'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='course_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseplan'),
        ),
    ]
