# Generated by Django 5.2.9 on 2026-06-02 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_options_alter_courseplan_options_and_more'),
        ('shop', '0004_alter_cartitem_options_alter_cartitem_course_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='course_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseplan', verbose_name='Varianta kurzu'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant', verbose_name='Varianta produktu'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Množství'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Zákazník'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='length',
            field=models.CharField(blank=True, choices=[('7', '7 metrů'), ('10', '10 metrů')], max_length=5, null=True, verbose_name='Délka'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='type',
            field=models.CharField(blank=True, choices=[('no_loop', 'Bez očka'), ('shoulder', 'Očko přes rameno'), ('hand_loop', 'Poutko na ruku')], max_length=20, null=True, verbose_name='Typ zakončení'),
        ),
    ]
