# Generated by Django 5.2.9 on 2026-06-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cartitem_course_plan_alter_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale_locked',
            field=models.BooleanField(default=False, help_text='Zákazník vidí zámeček místo tlačítka. Produkt nejde rozkliknout ani koupit.', verbose_name='Prodej uzamčen'),
        ),
    ]
