# Generated by Django 5.2.9 on 2026-07-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_is_sale_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='length',
            field=models.CharField(blank=True, choices=[('3', '3 metry'), ('5', '5 metrů'), ('7', '7 metrů'), ('10', '10 metrů')], max_length=5, null=True, verbose_name='Délka'),
        ),
    ]
