# Generated by Django 5.2.9 on 2026-07-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_length_3m_5m'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='code',
            field=models.SlugField(blank=True, verbose_name='Kód varianty'),
        ),
    ]
