# Generated by Django 5.2.9 on 2026-07-12 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Město / lokalita')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL identifikátor')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Pořadí')),
            ],
            options={
                'verbose_name': 'Lokalita',
                'verbose_name_plural': 'Lokality',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Jméno trenéra')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail trenéra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('google_calendar_id', models.CharField(blank=True, default='primary', max_length=255, verbose_name='ID Google kalendáře')),
                ('google_oauth_token', models.TextField(blank=True, verbose_name='Google OAuth token (JSON)')),
                ('google_connected', models.BooleanField(default=False, verbose_name='Google kalendář připojen')),
                ('locations', models.ManyToManyField(blank=True, related_name='trainers', to='trainings.location', verbose_name='Obsluhované lokality')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelský účet')),
            ],
            options={
                'verbose_name': 'Trenér',
                'verbose_name_plural': 'Trenéři',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('start_time', models.TimeField(verbose_name='Začátek')),
                ('end_time', models.TimeField(verbose_name='Konec')),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='Délka slotu (min)')),
                ('session_type', models.CharField(choices=[('individual', 'Individuální'), ('group', 'Skupinová')], default='individual', max_length=20, verbose_name='Typ lekce')),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Individuální = 1, skupinová = počet míst na jeden slot.', verbose_name='Kapacita slotu (počet účastníků)')),
                ('is_active', models.BooleanField(default=True, help_text='Odškrtnutím okno zablokujete (sloty se nenabízejí).', verbose_name='Aktivní')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='windows', to='trainings.location', verbose_name='Lokalita')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='windows', to='trainings.trainer', verbose_name='Trenér')),
            ],
            options={
                'verbose_name': 'Časové okno',
                'verbose_name_plural': 'Časová okna',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Začátek')),
                ('end', models.DateTimeField(verbose_name='Konec')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='Kapacita')),
                ('session_type', models.CharField(choices=[('individual', 'Individuální'), ('group', 'Skupinová')], default='individual', max_length=20, verbose_name='Typ lekce')),
                ('status', models.CharField(choices=[('open', 'Volný'), ('blocked', 'Blokovaný')], default='open', max_length=20, verbose_name='Stav')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='trainings.location', verbose_name='Lokalita')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='trainings.trainer', verbose_name='Trenér')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='trainings.availabilitywindow', verbose_name='Okno')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Sloty',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='TrainingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=120, verbose_name='Příjmení')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('dog_name', models.CharField(max_length=120, verbose_name='Jméno psa')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('status', models.CharField(choices=[('confirmed', 'Potvrzeno'), ('canceled', 'Zrušeno'), ('completed', 'Absolvováno')], default='confirmed', max_length=20, verbose_name='Stav')),
                ('google_event_id', models.CharField(blank=True, max_length=255, verbose_name='ID Google události')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Zrušeno dne')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='trainings.trainingslot', verbose_name='Slot')),
            ],
            options={
                'verbose_name': 'Rezervace tréninku',
                'verbose_name_plural': 'Rezervace tréninků',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingslot',
            constraint=models.UniqueConstraint(fields=('trainer', 'start'), name='uniq_trainer_slot_start'),
        ),
        migrations.AddConstraint(
            model_name='trainingreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('slot', 'user'), name='uniq_active_slot_user'),
        ),
    ]
