# Generated by Django 5.2.9 on 2026-07-14 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_seed_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitywindow',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifikátor zdrojové události v Google kalendáři (jen u importu).', max_length=1024, verbose_name='ID Google události'),
        ),
        migrations.AddField(
            model_name='availabilitywindow',
            name='source',
            field=models.CharField(choices=[('manual', 'Ručně v adminu'), ('google', 'Google kalendář')], default='manual', help_text='Okno zadané ručně, nebo naimportované z Google kalendáře.', max_length=20, verbose_name='Původ'),
        ),
        migrations.CreateModel(
            name='AvailabilityCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(help_text='ID dedikovaného Google kalendáře pro tuto lokalitu (Nastavení kalendáře → Integrovat kalendář → ID kalendáře).', max_length=255, verbose_name='ID Google kalendáře dostupnosti')),
                ('default_slot_minutes', models.PositiveSmallIntegerField(default=60, help_text='Na jak dlouhé sloty se okno z kalendáře rozdělí.', verbose_name='Výchozí délka slotu (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Poznámka')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_calendars', to='trainings.location', verbose_name='Lokalita')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_calendars', to='trainings.trainer', verbose_name='Trenér')),
            ],
            options={
                'verbose_name': 'Kalendář dostupnosti',
                'verbose_name_plural': 'Kalendáře dostupnosti',
                'constraints': [models.UniqueConstraint(fields=('trainer', 'location'), name='unique_availability_calendar_per_trainer_location')],
            },
        ),
    ]
